const fs = require('fs');
const code = fs.readFileSync('src/pages/ProjectDetail.tsx', 'utf8');

const startStr = '<div className="space-y-8">';
const endStr = '      <AnimatePresence>\n        {/* Team Member Modal */}';

const start = code.indexOf(startStr);
const end = code.indexOf(endStr);

if (start === -1 || end === -1) {
  console.log('Could not find start or end');
  process.exit(1);
}

const block = code.substring(start, end);

const getBlock = (sStr, eStr, offset = 6) => {
  const s = block.indexOf(sStr);
  if (s === -1) return '<div>Error finding block: ' + sStr.substring(0, 20) + '</div>';
  const e = block.indexOf(eStr, s);
  if (e === -1) return '<div>Error finding end of block</div>';
  return block.substring(s, e + offset);
};

const personasBlock = getBlock('<div className="bg-white dark:bg-zinc-900 rounded-3xl border border-zinc-200 dark:border-zinc-800 shadow-sm p-8">', 'No personas selected for this project.', 45);
const teamBlock = getBlock('<div className="bg-white dark:bg-zinc-900 rounded-3xl border border-zinc-200 dark:border-zinc-800 shadow-sm p-8">', 'No team members added yet.', 33);
const statusBlock = getBlock('<div className="bg-zinc-900 rounded-3xl p-8 text-white shadow-xl relative overflow-hidden flex flex-col justify-between min-h-[320px]">', 'at {new Date(project.updatedAt).toLocaleTimeString()}</p>', 64);
const strategyBlock = getBlock('<div className="lg:col-span-2 bg-white dark:bg-zinc-900 rounded-3xl border border-zinc-200 dark:border-zinc-800 shadow-sm overflow-hidden flex flex-col">', 'Add Tag', 32);
const goalsBlock = getBlock('<div className="lg:col-span-2 bg-white dark:bg-zinc-900 rounded-3xl border border-zinc-200 dark:border-zinc-800 shadow-sm p-8">', 'Expected Outcomes', 1500);
const focusBlock = getBlock('<div className="bg-white dark:bg-zinc-900 rounded-3xl border border-zinc-200 dark:border-zinc-800 shadow-sm p-8 space-y-6">', 'No improvement focus defined.', 36);
const journeysBlock = getBlock('<div className="lg:col-span-2 flex flex-col">', 'No implemented maps yet.', 31);
const processMapsBlock = getBlock('<div className="bg-white dark:bg-zinc-900 rounded-3xl border border-zinc-200 dark:border-zinc-800 shadow-sm overflow-hidden flex flex-col">', 'No process maps yet.', 27);
const raidBlock = getBlock('<div className="bg-white dark:bg-zinc-900 rounded-3xl border border-zinc-200 dark:border-zinc-800 shadow-sm flex flex-col overflow-hidden">', 'No RAID items identified yet.', 36);

let replacement = '<DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={handleDragEnd}>\n';
replacement += '        <SortableContext items={layout} strategy={rectSortingStrategy}>\n';
replacement += '          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">\n';
replacement += '            {layout.map(widgetId => {\n';
replacement += '              switch(widgetId) {\n';
replacement += '                case "personas":\n';
replacement += '                  return (\n';
replacement += '                    <SortableWidget key="personas" id="personas" className="col-span-full">\n';
replacement += '                      ' + personasBlock + '\n';
replacement += '                    </SortableWidget>\n';
replacement += '                  );\n';
replacement += '                case "team":\n';
replacement += '                  return (\n';
replacement += '                    <SortableWidget key="team" id="team" className="col-span-full">\n';
replacement += '                      ' + teamBlock + '\n';
replacement += '                    </SortableWidget>\n';
replacement += '                  );\n';
replacement += '                case "status":\n';
replacement += '                  return (\n';
replacement += '                    <SortableWidget key="status" id="status" className="col-span-1">\n';
replacement += '                      ' + statusBlock + '\n';
replacement += '                    </SortableWidget>\n';
replacement += '                  );\n';
replacement += '                case "strategy":\n';
replacement += '                  return (\n';
replacement += '                    <SortableWidget key="strategy" id="strategy" className="lg:col-span-2">\n';
replacement += '                      ' + strategyBlock + '\n';
replacement += '                    </SortableWidget>\n';
replacement += '                  );\n';
replacement += '                case "goals":\n';
replacement += '                  return (\n';
replacement += '                    <SortableWidget key="goals" id="goals" className="lg:col-span-2">\n';
replacement += '                      ' + goalsBlock + '\n';
replacement += '                    </SortableWidget>\n';
replacement += '                  );\n';
replacement += '                case "focus":\n';
replacement += '                  return (\n';
replacement += '                    <SortableWidget key="focus" id="focus" className="col-span-1">\n';
replacement += '                      ' + focusBlock + '\n';
replacement += '                    </SortableWidget>\n';
replacement += '                  );\n';
replacement += '                case "journeys":\n';
replacement += '                  return (\n';
replacement += '                    <SortableWidget key="journeys" id="journeys" className="lg:col-span-2">\n';
replacement += '                      ' + journeysBlock + '\n';
replacement += '                    </SortableWidget>\n';
replacement += '                  );\n';
replacement += '                case "process_maps":\n';
replacement += '                  return (\n';
replacement += '                    <SortableWidget key="process_maps" id="process_maps" className="col-span-1">\n';
replacement += '                      ' + processMapsBlock + '\n';
replacement += '                    </SortableWidget>\n';
replacement += '                  );\n';
replacement += '                case "raid":\n';
replacement += '                  return (\n';
replacement += '                    <SortableWidget key="raid" id="raid" className="col-span-full">\n';
replacement += '                      ' + raidBlock + '\n';
replacement += '                    </SortableWidget>\n';
replacement += '                  );\n';
replacement += '                case "storyboards":\n';
replacement += '                  return (\n';
replacement += '                    <SortableWidget key="storyboards" id="storyboards" className="col-span-full">\n';
replacement += '                      <div className="bg-white dark:bg-zinc-900 rounded-3xl border border-zinc-200 dark:border-zinc-800 shadow-sm p-8">\n';
replacement += '                        <div className="flex items-center justify-between mb-6">\n';
replacement += '                          <div className="flex items-center gap-3">\n';
replacement += '                            <div className="p-2 bg-indigo-100 text-indigo-600 rounded-lg">\n';
replacement += '                              <LayoutTemplate className="w-5 h-5" />\n';
replacement += '                            </div>\n';
replacement += '                            <h3 className="font-bold text-zinc-900 dark:text-white text-lg">Storyboards</h3>\n';
replacement += '                          </div>\n';
replacement += '                          <button \n';
replacement += '                            onClick={() => onNavigate("storyboards")}\n';
replacement += '                            className="p-2 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-lg text-zinc-400 hover:text-indigo-600 transition-all shadow-sm"\n';
replacement += '                          >\n';
replacement += '                            <Plus className="w-4 h-4" />\n';
replacement += '                          </button>\n';
replacement += '                        </div>\n';
replacement += '                        <div className="text-center py-8 text-zinc-400 text-sm">\n';
replacement += '                          Click + to manage storyboards\n';
replacement += '                        </div>\n';
replacement += '                      </div>\n';
replacement += '                    </SortableWidget>\n';
replacement += '                  );\n';
replacement += '                case "kanban":\n';
replacement += '                  return (\n';
replacement += '                    <SortableWidget key="kanban" id="kanban" className="col-span-full">\n';
replacement += '                      <div className="bg-white dark:bg-zinc-900 rounded-3xl border border-zinc-200 dark:border-zinc-800 shadow-sm p-8">\n';
replacement += '                        <div className="flex items-center justify-between mb-6">\n';
replacement += '                          <div className="flex items-center gap-3">\n';
replacement += '                            <div className="p-2 bg-indigo-100 text-indigo-600 rounded-lg">\n';
replacement += '                              <FolderKanban className="w-5 h-5" />\n';
replacement += '                            </div>\n';
replacement += '                            <h3 className="font-bold text-zinc-900 dark:text-white text-lg">Kanban Board</h3>\n';
replacement += '                          </div>\n';
replacement += '                          <button \n';
replacement += '                            onClick={() => onNavigate("kanban")}\n';
replacement += '                            className="p-2 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-lg text-zinc-400 hover:text-indigo-600 transition-all shadow-sm"\n';
replacement += '                          >\n';
replacement += '                            <ChevronRight className="w-4 h-4" />\n';
replacement += '                          </button>\n';
replacement += '                        </div>\n';
replacement += '                        <div className="text-center py-8 text-zinc-400 text-sm">\n';
replacement += '                          Click to view Kanban Board\n';
replacement += '                        </div>\n';
replacement += '                      </div>\n';
replacement += '                    </SortableWidget>\n';
replacement += '                  );\n';
replacement += '                default:\n';
replacement += '                  return null;\n';
replacement += '              }\n';
replacement += '            })}\n';
replacement += '          </div>\n';
replacement += '        </SortableContext>\n';
replacement += '      </DndContext>\n';

const newCode = code.substring(0, start) + replacement + code.substring(end);
fs.writeFileSync('src/pages/ProjectDetail.tsx', newCode);
console.log('Done');
